### ISSUE TITLE
Can I stream audio back to connect through the same kvs stream?

### ISSUE THREAD

**Issue by Caet-pip** [amazon-connect/connect-kvs-consumer-demo#4]
Hello,

I wanted to know if I can send back an audio response from external application to the kvs stream which will be played to the customer? As far as I am aware and the documentation describes audio can only be streamed from audio connector to kvs which can be used by an external application but I haven't seen any mention of sending a audio response back by writing audio to the same stream from external application. 

Thanks!

**Comment by rmconst** [comment]
Amazon Connect only outputs audio through these Kinesis Video streams. There is currently no plan to support ingesting audio through them.
